/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lauri Purhonen (https://sketchfab.com/LauriPurhonen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/ddc40bb0900544959f02d3ff83c32615
title: Animal cell - Downloadable
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Bio_animal cell/animal.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.2, 0.29, 0]} scale={[1.19, 1.27, 1.27]}>
          <mesh geometry={nodes.Sphere001_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-0.38, -3.27, 0.02]} rotation={[0, -0.06, 3.06]} scale={[0.05, 0.05, 0.05]}>
          <mesh geometry={nodes.Sphere002_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-0.39, 0.61, -0.01]} scale={1.14}>
          <mesh geometry={nodes.Icosphere_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.39, 0.61, -0.01]} scale={1.14}>
          <mesh geometry={nodes.BezierCurve_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[1.15, -2.2, -0.37]} rotation={[0, 0, 0.76]} scale={[0.41, 0.41, 0.41]}>
          <mesh geometry={nodes.BezierCurve002_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[0.2, 0.2, -0.13]} scale={[1.13, 1.2, 1.2]}>
          <mesh geometry={nodes.Sphere_0.geometry} material={materials.Material} />
        </group>
        <group position={[1.92, 0.2, -0.21]} rotation={[0.01, -0.04, 1.65]} scale={[0.19, 0.19, 0.19]}>
          <mesh geometry={nodes.Roundcube000_0.geometry} material={materials['Material.011']} />
        </group>
        <group position={[-0.38, 0.55, 0.2]} scale={0.26}>
          <mesh geometry={nodes.Roundcube001_0.geometry} material={materials['Material.009']} />
        </group>
        <group position={[-0.38, 0.62, 0]} scale={0.98}>
          <mesh geometry={nodes.Roundcube_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-0.39, 0.61, -0.01]} scale={1.14}>
          <mesh geometry={nodes.Icosphere002_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[-0.38, -3.27, 0.02]} rotation={[0, -0.06, 3.06]} scale={[0.05, 0.05, 0.05]}>
          <mesh geometry={nodes.Sphere005_0.geometry} material={materials['Material.007']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/animal.gltf')
