/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sara Carena (https://sketchfab.com/saracarena1)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/badlands-spain-db8f95dddda44cf7b57755d9253c8366
title: Badlands, Spain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Geo_Badland-Spain/badland.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.88, 0.06, 0.87]} rotation={[-2.56, 0.86, 2.53]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Model_material2_0.geometry} material={nodes.Model_material2_0.material} />
          <mesh geometry={nodes.Model_material2_0_1.geometry} material={nodes.Model_material2_0_1.material} />
          <mesh geometry={nodes.Model_material2_0_2.geometry} material={nodes.Model_material2_0_2.material} />
          <mesh geometry={nodes.Model_material0_0.geometry} material={nodes.Model_material0_0.material} />
          <mesh geometry={nodes.Model_material0_0_1.geometry} material={nodes.Model_material0_0_1.material} />
          <mesh geometry={nodes.Model_material0_0_2.geometry} material={nodes.Model_material0_0_2.material} />
          <mesh geometry={nodes.Model_material3_0.geometry} material={nodes.Model_material3_0.material} />
          <mesh geometry={nodes.Model_material3_0_1.geometry} material={nodes.Model_material3_0_1.material} />
          <mesh geometry={nodes.Model_material3_0_2.geometry} material={nodes.Model_material3_0_2.material} />
          <mesh geometry={nodes.Model_material1_0.geometry} material={nodes.Model_material1_0.material} />
          <mesh geometry={nodes.Model_material1_0_1.geometry} material={nodes.Model_material1_0_1.material} />
          <mesh geometry={nodes.Model_material1_0_2.geometry} material={nodes.Model_material1_0_2.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/badland.gltf')
