/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: E-learning University Medical Center Groningen (https://sketchfab.com/eLearningUMCG)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/models/e769645f40fc47c38b89bcfc6b8b4d44
title: Human Eukaryotic Cell and its main components
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Bio_human_eukaryotic_cell/eukaryotic_cell.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1.41, 0.56, -1.85]} rotation={[-1.58, -1.46, -3.09]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Nucleus_membrane_Nucleus_membrane_0.geometry} material={materials.Nucleus_membrane} />
            <mesh geometry={nodes.Nuclear_pores_Nuclear_pores_0.geometry} material={materials.Nuclear_pores} />
            <mesh geometry={nodes.Nucleolus_Nucleolus_0.geometry} material={materials.Nucleolus} />
            <mesh geometry={nodes.Heterochromatin_Heterochromatin_0.geometry} material={materials.Heterochromatin} />
            <mesh geometry={nodes.Microfilaments2_Microfilaments2_0.geometry} material={materials.Microfilaments2} />
            <mesh geometry={nodes.Microfilaments_Microfilaments_0.geometry} material={materials.Microfilaments} />
            <mesh geometry={nodes.Golgi_Golgi_0.geometry} material={materials.Golgi} />
            <mesh geometry={nodes.Rer_Rer_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Ribosomes_Ribosomes_0.geometry} material={materials.Ribosomes} />
            <mesh geometry={nodes.Proteins_Proteins_0.geometry} material={materials.Proteins} />
            <mesh
              geometry={nodes.Mitochondria_external_membranes_Mitochondria_external_membranes_0.geometry}
              material={materials.Mitochondria_external_membranes}
            />
            <mesh geometry={nodes.Endosome_content_Endosome_content_0.geometry} material={materials.Endosome_content} />
            <mesh
              geometry={nodes.Endosome_external_membrane_Endosome_external_membrane_0.geometry}
              material={materials.Endosome_external_membrane}
            />
            <mesh
              geometry={nodes.Endosome_internal_membrane_Endosome_internal_membrane_0.geometry}
              material={materials.Endosome_internal_membrane}
            />
            <mesh geometry={nodes.Centrioles_Centrioles_0.geometry} material={materials.Centrioles} />
            <mesh geometry={nodes.Cell_membrane2_Cell_membrane2_0.geometry} material={materials.Cell_membrane2} />
            <mesh geometry={nodes.Lysosome_Lysosome_0.geometry} material={materials.Lysosome} />
            <mesh geometry={nodes.Lysosome_content_Lysosome_content_0.geometry} material={materials.Lysosome_content} />
            <mesh
              geometry={nodes.Mitochondria_inside_Mitochondria_inside_0.geometry}
              material={materials.Mitochondria_inside}
            />
            <mesh geometry={nodes.Rna_Rna_0.geometry} material={materials.material_20} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eukaryotic_cell.gltf')
