/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: kdreamer (https://sketchfab.com/kdreamer)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/india-c86b16b141e54d2d844b740941bedb0c
title: india
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Geo_India/india.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_1.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_1.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_2.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_2.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_3.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_3.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_4.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_4.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_5.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_5.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_6.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_6.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_7.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_7.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_8.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_8.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_9.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_9.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_10.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_10.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_11.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_11.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_12.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_12.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_13.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_13.material}
          />
          <mesh
            geometry={nodes.cleanerpPlane1_1_lambert1_0_14.geometry}
            material={nodes.cleanerpPlane1_1_lambert1_0_14.material}
          />
          <mesh geometry={nodes.cleanerpCube1_0_lambert2_0.geometry} material={materials.lambert2} />
          <group position={[-4.92, 1.36, 4.22]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow1_lambert8_0.geometry} material={materials.lambert8} />
          </group>
          <group position={[0.15, 1.36, 2.55]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow2_lambert4_0.geometry} material={nodes.arrow2_lambert4_0.material} />
          </group>
          <group position={[-0.68, 1.63, -6.07]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow3_lambert4_0.geometry} material={nodes.arrow3_lambert4_0.material} />
          </group>
          <group position={[-4.86, 1.36, -3.39]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow4_lambert4_0.geometry} material={nodes.arrow4_lambert4_0.material} />
          </group>
          <group position={[-1.24, 1.36, -0.37]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow5_lambert4_0.geometry} material={nodes.arrow5_lambert4_0.material} />
          </group>
          <group position={[-2.95, 1.36, -1.6]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow6_lambert4_0.geometry} material={nodes.arrow6_lambert4_0.material} />
          </group>
          <group position={[1.11, 1.36, -1.27]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow7_lambert4_0.geometry} material={nodes.arrow7_lambert4_0.material} />
          </group>
          <group position={[-4.97, 1.65, -10.44]} rotation={[Math.PI, 0, 0]}>
            <mesh geometry={nodes.arrow8_lambert4_0.geometry} material={nodes.arrow8_lambert4_0.material} />
          </group>
          <group position={[-1.15, 2.25, -6.26]} rotation={[0, -0.36, 0]} scale={0.08}>
            <mesh geometry={nodes.polySurface1_lambert9_0.geometry} material={nodes.polySurface1_lambert9_0.material} />
          </group>
          <group position={[-5.82, 2.25, -10.45]} scale={0.07}>
            <mesh geometry={nodes.polySurface2_lambert9_0.geometry} material={nodes.polySurface2_lambert9_0.material} />
          </group>
          <group position={[-5.87, 1.97, 4.72]} rotation={[0, 0.52, 0]} scale={[0.09, 0.09, 0.09]}>
            <mesh geometry={nodes.polySurface3_lambert9_0.geometry} material={nodes.polySurface3_lambert9_0.material} />
          </group>
          <group position={[-0.93, 1.97, 2.54]} scale={0.09}>
            <mesh geometry={nodes.polySurface4_lambert9_0.geometry} material={nodes.polySurface4_lambert9_0.material} />
          </group>
          <group position={[-5.68, 1.97, -3.4]} scale={0.08}>
            <mesh geometry={nodes.polySurface5_lambert9_0.geometry} material={nodes.polySurface5_lambert9_0.material} />
          </group>
          <group position={[-2.17, 1.98, -0.38]} scale={0.09}>
            <mesh geometry={nodes.polySurface6_lambert9_0.geometry} material={nodes.polySurface6_lambert9_0.material} />
          </group>
          <group position={[-4.06, 2, -1.61]} scale={0.1}>
            <mesh geometry={nodes.polySurface7_lambert9_0.geometry} material={nodes.polySurface7_lambert9_0.material} />
          </group>
          <group position={[-0.07, 2.04, -1.31]} scale={0.07}>
            <mesh geometry={nodes.polySurface8_lambert9_0.geometry} material={nodes.polySurface8_lambert9_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/india.gltf')
