/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: callanbentley (https://sketchfab.com/callanbentley)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/tectonic-structure-to-identify-and-interpret-96df49b2f3e64582857eea2459b9d7f8
title: Tectonic structure to identify and interpret
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Geo_Tectonic/tectonic.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.8, 0.5, 0.18]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[-14.79, -26.96, 17.39]} rotation={[-1.59, 0.68, -0.1]}>
                <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
                <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
                <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
                <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
                <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
                <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
                <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
                <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tectonic.gltf')
